[extend]
useDefault = true

[allowlist]
paths = [
  '''.sonarqube''',
  '''node_modules''',
  '''dist''',
  '''.next''',
  '''bin''',
  '''obj''',
  '''keycloak.json''',
  '''infra''',
  '''compose.yml''',
  '''README.md'''
]