import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/app/nav/Navbar";
import React from "react";
import ReduxProvider from "@/app/redux/provider";
import ToasterProvider from "@/app/components/Toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
      <ReduxProvider>
          <ToasterProvider />
          <Navbar />
          <main className="container mx-auto px-5 pt-10">
              {children}
          </main>
      </ReduxProvider>
      </body>
    </html>
  );
}
