deployments:
  - name: auction
    replicas: 1
    image: davidlihor/auction-svc
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 80
        protocol: TCP
      - name: grpc
        containerPort: 7050
        protocol: TCP

  - name: search
    replicas: 1
    image: davidlihor/search-svc
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

  - name: bid
    replicas: 1
    image: davidlihor/bid-svc
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

  - name: notification
    replicas: 1
    image: davidlihor/notification-svc
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

  - name: gateway
    replicas: 1
    image: davidlihor/gateway-svc
    volumes:
      - name: yarp-config
        mountPath: /app/appsettings.Production.json
        subPath: appsettings.Production.json
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 80
        protocol: TCP

  - name: identity
    replicas: 1
    image: quay.io/keycloak/keycloak
    volumes:
      - name: keycloak-config
        mountPath: /opt/keycloak/data/import/realm-export.json
        subPath: realm-export.json
    args:
      - start-dev
      - --import-realm
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

  - name: webapp
    replicas: 1
    image: davidlihor/web-app
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 3000
        protocol: TCP

  - name: postgres
    replicas: 1
    image: postgres
    volumes:
      - name: postgres
        mountPath: /postgres-data
    config: true
    secrets: true
    ports:
      - name: http
        containerPort: 5432
        protocol: TCP

  - name: mongodb
    replicas: 1
    image: mongo
    volumes:
      - name: mongodb
        mountPath: /data/db
    secrets: true
    ports:
      - name: http
        containerPort: 27017
        protocol: TCP

  - name: rabbitmq
    replicas: 1
    image: rabbitmq:3-management
    volumes:
      - name: rabbitmq
        mountPath: /var/lib/rabbitmq
    secrets: true
    ports:
      - name: rbmq-mgmt-port
        containerPort: 15672
        protocol: TCP
      - name: rbmq-msg-port
        containerPort: 5672
        protocol: TCP
