apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
      - repoURL: https://helm.releases.hashicorp.com
        chart: vault
        targetRevision: 0.31.0
        helm:
          valueFiles: []
      - repoURL: https://github.com/davidlihor/Carsties
        targetRevision: HEAD
        path: argocd/apps/infrastructure/vault
        name: custom-values
  template:
    helm:
      valueFiles:
        - $custom-values/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
