apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.31.0
    helm:
      values: |
        server:
          serviceAccount:
            create: false
            name: vault
          dataStorage:
            enabled: true
            size: 1Gi
            storageClass: gp2
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              storageClass: gp2
              config: |
                storage "raft" {
                  path    = "/vault/data"
                }
                listener "tcp" {
                  address     = "[::]:8200"
                  tls_disable = 1
                }
                seal "awskms" {
                  region     = "us-east-1"
                  kms_key_id = "${VAULT_KMS_ARN}"
                }
                service_registration "kubernetes" {}
          extraSecretEnvironmentVars:
            - envName: VAULT_KMS_ARN
              secretName: vault-kms-arn
              secretKey: VAULT_KMS_ARN
          extraConfig: |
            seal "awskms" {
              region     = "us-east-1"
              kms_key_id = "${VAULT_KMS_ARN}"
            }
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
