apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.31.0
    helm:
      values: |
        server:
          serviceAccount:
            create: false
            name: vault
          dataStorage:
            enabled: true
            size: 1Gi
            storageClass: gp2
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              storageClass: gp2
              config: |
                storage "raft" {
                  path    = "/vault/data"
                }
                listener "tcp" {
                  address     = "[::]:8200"
                  tls_disable = 1
                }
                seal "awskms" {
                  region     = "us-east-1"
                }
                service_registration "kubernetes" {}
          extraSecretEnvironmentVars:
              - envName: VAULT_AWSKMS_SEAL_KEY_ID
                secretName: vault-kms-arn-secret
                secretKey: kms_key_id
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
