apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.31.0
    helm:
      values: |
        serviceAccount:
          create: false
          name: vault
        dataStorage:
          enabled: true
          size: 1Gi
          storageClass: gp2
        ha:
          enabled: true
          replicas: 3
          raft:
            enabled: true
            setNodeId: true
            storageClass: gp2
            config: |
              storage "raft" {
                path    = "/vault/data"
              }
              listener "tcp" {
                address     = "[::]:8200"
                tls_disable = 1
              }
              service_registration "kubernetes" {}
          extraEnvironmentVars: {}
          seal:
            awskms:
              enabled: true
              region: us-east-1
              kmsKeyId:
                secret:
                  name: vault-kms-arn
                  key: arn
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
