apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "ResourceWait=true"
spec:
  project: default
  source:
    repoURL: https://github.com/davidlihor/Carsties
    targetRevision: HEAD
    path: argocd/apps/infrastructure/eso-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true