apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgresSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  connectionString: Server=postgres-clusterip;User Id=postgres;Password=postgresSecretPw;Database=auctions
  authority: http://identity-clusterip/realms/carsties-auth
  issuer: https://id.carsties.local/realms/carsties-auth
  clientId: nextApp
  audience: account
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  authority: http://identity-clusterip/realms/carsties-auth
  issuer: https://id.carsties.local/realms/carsties-auth
  clientId: nextApp
  audience: account
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: mongoUn
  password: mongoSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbitUn
  password: rabbitSecretPw
---
apiVersion: v1
kind: Secret
metadata:
  name: bid-secret
type: Opaque
stringData:
  connectionString: mongodb://mongoUn:mongoSecretPw@mongodb-clusterip
  authority: http://identity-clusterip/realms/carsties-auth
  issuer: https://id.carsties.local/realms/carsties-auth
  clientId: nextApp
  audience: account
---
apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
type: Opaque
stringData:
  kc_db_url: jdbc:postgresql://postgres-clusterip:5432/keycloak
  kc_db_username: postgres
  kc_db_password: postgresSecretPw
  kc_bootstrap_admin_username: admin
  kc_bootstrap_admin_password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
stringData:
  connectionString: mongodb://mongoUn:mongoSecretPw@mongodb-clusterip
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  authSecret: thisisevenmoresecretthanprevioussecrets
  client_id: nextApp
  client_secret: EHS9uO5LB6Rl87C7avct2SOt6jfenmCu
  realm: carsties-auth