name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env: 
      continue: "false"
    strategy:
      matrix:
        service:
          - name: "davidlihor/auction-svc"
            path: "src/AuctionService"
          - name: "davidlihor/search-svc"
            path: "src/SearchService"
          - name: "davidlihor/bid-svc"
            path: "src/BiddingService"
          - name: "davidlihor/gateway-svc"
            path: "src/GatewayService"  
          - name: "davidlihor/notification-svc"
            path: "src/NotificationService"    
          - name: "davidlihor/web-app"
            path: "frontend/web-app"          

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 2

    - name: Check Changes
      run: |
        if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
          echo "No changes in ${{matrix.service.path}}."
          echo "continue=false" >> $GITHUB_ENV
        else 
          echo "Changes found in ${{matrix.service.path}}."
          echo "continue=true" >> $GITHUB_ENV
        fi
    
    - name: Set up Docker buildx
      if: env.continue == 'true'
      uses: docker/setup-buildx-action@v2
    
    - name: Login
      if: env.continue == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build and push docker image
      if: env.continue == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{matrix.service.path}}/Dockerfile
        push: true
        tags: ${{matrix.service.name}}:latest