{{- if $.Values.global.monitoring }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  namespace: monitoring
  labels:
    name: ingress-svc
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - prometheus.monitoring.local
        - grafana.monitoring.local
      secretName: monitoring-tls
  rules:
    - host: prometheus.monitoring.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
    - host: grafana.monitoring.local
      http:
        paths:    
          - pathType: Prefix
            path: /
            backend:
              service:
                name: prometheus-grafana
                port:
                  number: 80
{{- end }}