{{- range .Values.deployments }}
{{- if and .monitoring $.Values.global.monitoring }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .name }}-service-monitor
  namespace: monitoring
  labels:
    release: promstack
spec:
  namespaceSelector:
    matchNames:
      - {{ $.Values.global.namespace }}
  selector:
    matchLabels:
      app: {{ .name }}-clusterip
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
{{- end }}
{{- end }}